# Generated by Django 5.2.5 on 2025-08-27 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AmazonCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign_id",
                    models.IntegerField(unique=True, verbose_name="活动ID"),
                ),
                (
                    "campaign_name",
                    models.CharField(max_length=255, verbose_name="活动名称"),
                ),
                (
                    "campaign_type",
                    models.CharField(max_length=50, verbose_name="活动类型"),
                ),
                ("state", models.CharField(max_length=50, verbose_name="状态")),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="预算",
                    ),
                ),
                (
                    "budget_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="预算类型"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="开始日期"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "亚马逊广告活动",
                "verbose_name_plural": "亚马逊广告活动",
            },
        ),
        migrations.CreateModel(
            name="AmazonProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_id",
                    models.IntegerField(unique=True, verbose_name="配置文件ID"),
                ),
                (
                    "profile_name",
                    models.CharField(max_length=255, verbose_name="配置文件名称"),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="国家代码"
                    ),
                ),
                (
                    "marketplace_string_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="市场ID"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "亚马逊广告配置文件",
                "verbose_name_plural": "亚马逊广告配置文件",
            },
        ),
        migrations.CreateModel(
            name="AmazonAdGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad_group_id",
                    models.IntegerField(unique=True, verbose_name="广告组ID"),
                ),
                (
                    "ad_group_name",
                    models.CharField(max_length=255, verbose_name="广告组名称"),
                ),
                ("state", models.CharField(max_length=50, verbose_name="状态")),
                (
                    "default_bid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="默认出价",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_groups",
                        to="api.amazoncampaign",
                        verbose_name="广告活动",
                    ),
                ),
            ],
            options={
                "verbose_name": "亚马逊广告组",
                "verbose_name_plural": "亚马逊广告组",
            },
        ),
        migrations.CreateModel(
            name="AmazonKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword_id",
                    models.IntegerField(unique=True, verbose_name="关键词ID"),
                ),
                (
                    "keyword_text",
                    models.CharField(max_length=255, verbose_name="关键词文本"),
                ),
                (
                    "match_type",
                    models.CharField(max_length=50, verbose_name="匹配类型"),
                ),
                ("state", models.CharField(max_length=50, verbose_name="状态")),
                (
                    "bid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="出价",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="api.amazonadgroup",
                        verbose_name="广告组",
                    ),
                ),
            ],
            options={
                "verbose_name": "亚马逊关键词",
                "verbose_name_plural": "亚马逊关键词",
            },
        ),
        migrations.AddField(
            model_name="amazoncampaign",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="api.amazonprofile",
                verbose_name="配置文件",
            ),
        ),
        migrations.CreateModel(
            name="AmazonReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="报表ID"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(max_length=255, verbose_name="报表类型"),
                ),
                (
                    "status",
                    models.CharField(
                        default="IN_PROGRESS", max_length=50, verbose_name="状态"
                    ),
                ),
                (
                    "download_url",
                    models.URLField(blank=True, null=True, verbose_name="下载链接"),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="api.amazonprofile",
                        verbose_name="配置文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "亚马逊广告报表",
                "verbose_name_plural": "亚马逊广告报表",
            },
        ),
    ]
