# Generated by Django 5.2.5 on 2025-10-17 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["market_name", "sku"],
                "verbose_name": "产品",
                "verbose_name_plural": "产品列表",
            },
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("market_name", "sku", "asin", "fnsku")},
        ),
    ]
