# Generated by Django 5.2.5 on 2025-10-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_product_options_alter_product_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="market_place",
            new_name="market_name",
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={
                ("snapshot_date", "warehouse_name", "market_name", "fnsku", "condition")
            },
        ),
    ]
