# Generated by Django 5.2.5 on 2025-10-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_market_place_inventory_market_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={
                (
                    "snapshot_date",
                    "warehouse_name",
                    "market_name",
                    "fnsku",
                    "condition",
                    "sku",
                    "asin",
                )
            },
        ),
    ]
