# Generated by Django 5.2.5 on 2025-10-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_inventory_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="inventory",
            name="market_place",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="市场"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={
                (
                    "snapshot_date",
                    "warehouse_name",
                    "market_place",
                    "fnsku",
                    "condition",
                    "sku",
                    "asin",
                )
            },
        ),
    ]
