# Generated by Django 5.2.5 on 2025-10-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_inventory_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="adsspproduct",
            unique_together={
                (
                    "market_id",
                    "ad_id",
                    "create_date",
                    "portfolio_id",
                    "campaign_id",
                    "group_id",
                    "msku",
                    "asin",
                )
            },
        ),
    ]
