# Generated by Django 5.2.5 on 2025-10-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_adsspkeyword_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="adssptarget",
            unique_together={
                (
                    "market_id",
                    "target_id",
                    "create_date",
                    "portfolio_id",
                    "campaign_id",
                    "group_id",
                    "targeting_type",
                    "query",
                )
            },
        ),
    ]
