# Generated by Django 5.2.5 on 2025-10-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_adssptarget_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="adsspsearchterms",
            unique_together={
                (
                    "market_id",
                    "create_date",
                    "portfolio_id",
                    "campaign_id",
                    "group_id",
                    "keyword_id",
                    "match_type",
                    "query",
                )
            },
        ),
    ]
