# Generated by Django 5.2.5 on 2025-10-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_adssbkeyword_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="adssbcreative",
            unique_together={
                (
                    "market_id",
                    "ad_id",
                    "portfolio_id",
                    "campaign_id",
                    "create_date",
                    "group_id",
                    "creative_type",
                    "asins",
                )
            },
        ),
    ]
