# Generated by Django 5.2.5 on 2025-10-21 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_adssbcreative_unique_together"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction",
            name="api_transac_id_529dc6_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="api_transac_order_i_4b4487_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="api_transac_settlem_529626_idx",
        ),
        migrations.AlterField(
            model_name="adssbcampaign",
            name="create_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="创建日期",
            ),
        ),
        migrations.AlterField(
            model_name="adssbcreative",
            name="create_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="创建日期",
            ),
        ),
        migrations.AlterField(
            model_name="adssbkeyword",
            name="ads_type",
            field=models.CharField(
                default="SB", max_length=20, verbose_name="广告类型"
            ),
        ),
        migrations.AlterField(
            model_name="adssbkeyword",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="成本",
            ),
        ),
        migrations.AlterField(
            model_name="adssbkeyword",
            name="create_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="创建日期",
            ),
        ),
        migrations.AlterField(
            model_name="adsspkeyword",
            name="bid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="竞价",
            ),
        ),
        migrations.AlterField(
            model_name="adsspkeyword",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="成本",
            ),
        ),
        migrations.AlterField(
            model_name="adsspkeyword",
            name="create_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="创建日期"
            ),
        ),
        migrations.AlterField(
            model_name="adsspkeyword",
            name="market_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="市场ID"),
        ),
        migrations.AlterField(
            model_name="adsspplacement",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="成本",
            ),
        ),
        migrations.AlterField(
            model_name="adsspplacement",
            name="create_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="创建日期",
            ),
        ),
        migrations.AlterField(
            model_name="adsspproduct",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="成本",
            ),
        ),
        migrations.AlterField(
            model_name="adsspproduct",
            name="create_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="创建日期"
            ),
        ),
        migrations.AlterField(
            model_name="adsspproduct",
            name="market_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="市场ID"),
        ),
        migrations.AlterField(
            model_name="adsspsearchterms",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="成本",
            ),
        ),
        migrations.AlterField(
            model_name="adssptarget",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="成本",
            ),
        ),
        migrations.AlterField(
            model_name="adssptarget",
            name="create_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="创建日期"
            ),
        ),
        migrations.AlterField(
            model_name="adssptarget",
            name="market_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="市场ID"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["origin_sku"], name="api_transac_origin__8eefea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["description"], name="api_transac_descrip_c904d5_idx"
            ),
        ),
    ]
