# Generated by Django 5.2.5 on 2025-10-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_transaction_api_transac_id_529dc6_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adssbkeyword",
            name="bid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="出价",
            ),
        ),
    ]
