# Generated by Django 5.2.5 on 2025-10-21 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_adssbkeyword_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adsspsearchterms",
            name="create_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="创建日期",
            ),
        ),
    ]
