# Generated by Django 5.2.5 on 2025-10-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_adsspsearchterms_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adssdproduct",
            name="ad_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="广告ID"
            ),
        ),
        migrations.AlterField(
            model_name="adssdproduct",
            name="campaign_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="广告活动ID"
            ),
        ),
        migrations.AlterField(
            model_name="adssdproduct",
            name="group_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="广告组ID"
            ),
        ),
    ]
