# Generated by Django 5.2.5 on 2025-10-26 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_profitanalysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                (
                    "task_function",
                    models.CharField(max_length=255, verbose_name="任务函数路径"),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        help_text="格式: 分 时 日 月 周",
                        max_length=100,
                        verbose_name="Cron表达式",
                    ),
                ),
                (
                    "params",
                    models.TextField(
                        blank=True,
                        default="{}",
                        help_text="JSON格式的参数",
                        verbose_name="任务参数",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "激活"),
                            ("INACTIVE", "未激活"),
                            ("PAUSED", "暂停"),
                        ],
                        default="INACTIVE",
                        max_length=10,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_executed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后执行时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "定时任务",
                "verbose_name_plural": "定时任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "成功"),
                            ("FAILURE", "失败"),
                            ("RUNNING", "运行中"),
                        ],
                        default="RUNNING",
                        max_length=10,
                        verbose_name="执行状态",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="执行结果消息")),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "execution_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="执行时长(秒)"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="api.scheduledtask",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务执行日志",
                "verbose_name_plural": "任务执行日志",
                "ordering": ["-started_at"],
            },
        ),
    ]
