# Generated by Django 5.2.5 on 2025-10-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_scheduledtask_taskexecutionlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="qty_predicted_to_be_charged_ltsf12mo",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="qty_predicted_to_be_charged_ltsf6mo",
        ),
        migrations.AlterField(
            model_name="inventory",
            name="qty_to_be_charged_ltsf12mo",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="12个月内待计费数量"
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="qty_to_be_charged_ltsf6mo",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="6个月内待计费数量"
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="sku",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="sku"
            ),
        ),
        migrations.AlterField(
            model_name="profitanalysis",
            name="country_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="国家ID"),
        ),
        migrations.AlterField(
            model_name="profitanalysis",
            name="order_items",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="订单商品种类量"
            ),
        ),
        migrations.AlterField(
            model_name="profitanalysis",
            name="order_items_b2b",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="订单商品数（B2B）"
            ),
        ),
        migrations.AlterField(
            model_name="profitanalysis",
            name="orders",
            field=models.IntegerField(blank=True, null=True, verbose_name="订单数"),
        ),
        migrations.AlterField(
            model_name="profitanalysis",
            name="warehouse_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="仓储中心ID"),
        ),
        migrations.CreateModel(
            name="SalesForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "待同步"),
                            ("syncing", "同步中"),
                            ("success", "同步成功"),
                            ("failed", "同步失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="同步状态",
                    ),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后同步时间"
                    ),
                ),
                (
                    "sync_message",
                    models.TextField(blank=True, null=True, verbose_name="同步消息"),
                ),
                (
                    "gerpgo_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Gerpgo ID"
                    ),
                ),
                (
                    "gerpgo_data",
                    models.JSONField(blank=True, null=True, verbose_name="原始数据"),
                ),
                (
                    "market_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="市场ID"
                    ),
                ),
                (
                    "market_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="市场名称"
                    ),
                ),
                (
                    "asin",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ASIN"
                    ),
                ),
                (
                    "parent_asin",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="父ASIN"
                    ),
                ),
                (
                    "msku",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="MSKU"
                    ),
                ),
                (
                    "current_available_quantity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="当前可售库存"
                    ),
                ),
                (
                    "current_reserved_quantity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="当前预留库存"
                    ),
                ),
                (
                    "turnover_days",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="预计周转天数",
                    ),
                ),
                (
                    "daily_sales_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="日销售率",
                    ),
                ),
                (
                    "forecast_method",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="预估方法"
                    ),
                ),
                (
                    "forecast_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="预估开始日期"
                    ),
                ),
                (
                    "forecast_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="预估结束日期"
                    ),
                ),
                (
                    "forecasted_units",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="预估销售数量"
                    ),
                ),
                (
                    "forecasted_sales",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="预估销售额",
                    ),
                ),
                (
                    "month_1_forecast",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="第1个月预估销量"
                    ),
                ),
                (
                    "month_2_forecast",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="第2个月预估销量"
                    ),
                ),
                (
                    "month_3_forecast",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="第3个月预估销量"
                    ),
                ),
                (
                    "month_4_forecast",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="第4个月预估销量"
                    ),
                ),
                (
                    "month_5_forecast",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="第5个月预估销量"
                    ),
                ),
                (
                    "month_6_forecast",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="第6个月预估销量"
                    ),
                ),
                (
                    "month_7_forecast",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="第7个月预估销量"
                    ),
                ),
                (
                    "month_8_forecast",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="第8个月预估销量"
                    ),
                ),
                (
                    "month_9_forecast",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="第9个月预估销量"
                    ),
                ),
                (
                    "month_10_forecast",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="第10个月预估销量"
                    ),
                ),
                (
                    "month_11_forecast",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="第11个月预估销量"
                    ),
                ),
                (
                    "month_12_forecast",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="第12个月预估销量"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now=True, verbose_name="预估生成时间"),
                ),
            ],
            options={
                "verbose_name": "销售预估",
                "verbose_name_plural": "销售预估列表",
                "indexes": [
                    models.Index(fields=["asin"], name="api_salesfo_asin_0a574e_idx"),
                    models.Index(
                        fields=["parent_asin"], name="api_salesfo_parent__b864ea_idx"
                    ),
                    models.Index(
                        fields=["market_name"], name="api_salesfo_market__0734bd_idx"
                    ),
                    models.Index(
                        fields=["forecast_method"],
                        name="api_salesfo_forecas_1c5d2e_idx",
                    ),
                    models.Index(
                        fields=["generated_at"], name="api_salesfo_generat_0eacdf_idx"
                    ),
                ],
            },
        ),
    ]
