# Generated by Django 5.2.5 on 2025-11-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_remove_inventory_qty_predicted_to_be_charged_ltsf12mo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "待同步"),
                            ("syncing", "同步中"),
                            ("success", "同步成功"),
                            ("failed", "同步失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="同步状态",
                    ),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后同步时间"
                    ),
                ),
                (
                    "sync_message",
                    models.TextField(blank=True, null=True, verbose_name="同步消息"),
                ),
                (
                    "gerpgo_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Gerpgo ID"
                    ),
                ),
                (
                    "gerpgo_data",
                    models.JSONField(blank=True, null=True, verbose_name="原始数据"),
                ),
                (
                    "market_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="市场ID"
                    ),
                ),
                (
                    "market_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="市场名称"
                    ),
                ),
                (
                    "statistics_date",
                    models.DateField(blank=True, null=True, verbose_name="统计日期"),
                ),
                (
                    "msku",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="MSKU"
                    ),
                ),
                (
                    "asin",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ASIN"
                    ),
                ),
                (
                    "main_seller_rank",
                    models.IntegerField(blank=True, null=True, verbose_name="大类排名"),
                ),
                (
                    "seller_rank",
                    models.IntegerField(blank=True, null=True, verbose_name="小类排名"),
                ),
                (
                    "seller_rank_category",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="小类排名分类",
                    ),
                ),
                (
                    "main_seller_rank_category",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="大类排名分类",
                    ),
                ),
                (
                    "star",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="星级",
                    ),
                ),
                (
                    "review_quantity",
                    models.IntegerField(blank=True, null=True, verbose_name="评论数"),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="profitanalysis",
            options={"verbose_name": "销售数据", "verbose_name_plural": "销售数据"},
        ),
        migrations.AlterUniqueTogether(
            name="profitanalysis",
            unique_together={("market_id", "statistics_date", "msku", "asin")},
        ),
    ]
