# Generated by Django 5.2.5 on 2025-11-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_salesrank_alter_profitanalysis_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="promotion_deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "待同步"),
                            ("syncing", "同步中"),
                            ("success", "同步成功"),
                            ("failed", "同步失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="同步状态",
                    ),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后同步时间"
                    ),
                ),
                (
                    "sync_message",
                    models.TextField(blank=True, null=True, verbose_name="同步消息"),
                ),
                (
                    "gerpgo_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Gerpgo ID"
                    ),
                ),
                (
                    "gerpgo_data",
                    models.JSONField(blank=True, null=True, verbose_name="原始数据"),
                ),
                (
                    "market_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="市场ID"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="profitanalysis",
            name="bogus_discount_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="推广折扣成本",
            ),
        ),
        migrations.AddField(
            model_name="profitanalysis",
            name="bogus_orders",
            field=models.IntegerField(blank=True, null=True, verbose_name="推广订单量"),
        ),
        migrations.AddField(
            model_name="profitanalysis",
            name="bogus_sales_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="推广订单销售额",
            ),
        ),
        migrations.AddField(
            model_name="profitanalysis",
            name="natural_orders",
            field=models.IntegerField(blank=True, null=True, verbose_name="自然订单量"),
        ),
        migrations.AddField(
            model_name="profitanalysis",
            name="order_bogus_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="推广销量"),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={
                ("market_name", "sku", "asin", "fnsku", "item_condition", "sale_state")
            },
        ),
    ]
