# Generated by Django 5.2.5 on 2025-11-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_promotion_deal_profitanalysis_bogus_discount_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="qty_predicted_to_be_charged_ltsf12mo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="12个月内预测计费数量",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="qty_predicted_to_be_charged_ltsf6mo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="6个月内预测计费数量",
            ),
        ),
    ]
