# Generated by Django 5.2.5 on 2025-11-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_inventory_qty_predicted_to_be_charged_ltsf12mo_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="fbainventory",
            name="api_fbainve_add_tim_f42782_idx",
        ),
        migrations.RenameField(
            model_name="fbainventory",
            old_name="add_time",
            new_name="create_time",
        ),
        migrations.AlterUniqueTogether(
            name="fbainventory",
            unique_together={
                (
                    "msku",
                    "fnsku",
                    "asin",
                    "warehouse_name",
                    "create_time",
                    "warehouse_country",
                )
            },
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="available_qty",
            field=models.IntegerField(blank=True, null=True, verbose_name="可用数量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="available_turnover_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="availableTurnoverDays"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="avg_units_ordered_15_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="avgUnitsOrdered15Days"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="avg_units_ordered_30_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="avgUnitsOrdered30Days"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="avg_units_ordered_7_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="avgUnitsOrdered7Days"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="defective_qty",
            field=models.IntegerField(blank=True, null=True, verbose_name="次品数量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="erp_pending_inventory_qty",
            field=models.IntegerField(blank=True, null=True, verbose_name="待入库量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="erp_shipped_qty",
            field=models.IntegerField(blank=True, null=True, verbose_name="已发货量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="fba_inventory_health_status",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="FBA库存水平健康状态",
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="fba_min_quantity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="最低库存水平"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="fbm_available_quantity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="FBM可售数量"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="future_supply_buyable_quantity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="未来供应可买数量"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="good_qty",
            field=models.IntegerField(blank=True, null=True, verbose_name="良品数量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="historical_days_supply",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="历史天数供应"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="in_transit_qty",
            field=models.IntegerField(blank=True, null=True, verbose_name="在途量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="in_transit_turnover_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="inTransitTurnoverDays"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="inbound_total",
            field=models.IntegerField(blank=True, null=True, verbose_name="入库总数量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="inventory_age_0_to_30_days",
            field=models.IntegerField(blank=True, null=True, verbose_name="0-30天库存"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="inventory_age_181_to_270_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="181-270天库存"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="inventory_age_271_to_330_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="271-330天库存"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="inventory_age_31_to_60_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="31-60天库存"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="inventory_age_331_to_365_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="331-365天库存"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="inventory_age_365_plus_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="365天以上库存"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="inventory_age_61_to_90_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="61-90天库存"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="inventory_age_91_to_180_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="91-180天库存"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="inventory_turnover_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="inventoryTurnoverDays"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="local_available_quantity",
            field=models.IntegerField(blank=True, null=True, verbose_name="本地可售"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="lot_no_quantity",
            field=models.IntegerField(blank=True, null=True, verbose_name="交货量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="obsolete_qty",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="obsoleteQty"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="on_hand_qty",
            field=models.IntegerField(blank=True, null=True, verbose_name="在手数量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="order_quantity",
            field=models.IntegerField(blank=True, null=True, verbose_name="采购量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="pl_poLn_qty",
            field=models.IntegerField(blank=True, null=True, verbose_name="计采合交量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="plan_quantity",
            field=models.IntegerField(blank=True, null=True, verbose_name="计划量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="preassembly_plan_quantity",
            field=models.IntegerField(blank=True, null=True, verbose_name="装配计划量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="processed_reservation_qty",
            field=models.IntegerField(blank=True, null=True, verbose_name="已处理预占"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="product_delivery_days",
            field=models.IntegerField(blank=True, null=True, verbose_name="采购交期"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="purchase_plan_quantity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="采购计划数量"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="receiving_quantity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="货件正在接收"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="remote_available_quantity",
            field=models.IntegerField(blank=True, null=True, verbose_name="远程可售"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="researching_quantity",
            field=models.IntegerField(blank=True, null=True, verbose_name="调查中数量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="reservation_qty",
            field=models.IntegerField(blank=True, null=True, verbose_name="预占数量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="reserved_future_supply",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="预留未来供应"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="shipment_in_transit_turnover_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="shipmentInTransitTurnoverDays"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="shipment_total_turnover_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="shipmentTotalTurnoverDays"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="shipped_quantity",
            field=models.IntegerField(blank=True, null=True, verbose_name="货件已发货"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="single_quantity",
            field=models.IntegerField(blank=True, null=True, verbose_name="装箱量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="total_inventory_qty",
            field=models.IntegerField(blank=True, null=True, verbose_name="总库存数量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="total_quantity",
            field=models.IntegerField(blank=True, null=True, verbose_name="总数量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="total_turnover_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="totalTurnoverDays"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="transfer_pending_inventory_qty",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="调拨待出库（计划入库）"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="transfer_pending_shipment_qty",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="调拨待出运（待出运量）"
            ),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="unprocessed_reservation_qty",
            field=models.IntegerField(blank=True, null=True, verbose_name="未处理预占"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="unsellable_quantity",
            field=models.IntegerField(blank=True, null=True, verbose_name="不可售数量"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="warehouse_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="仓库ID"),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="working_quantity",
            field=models.IntegerField(blank=True, null=True, verbose_name="货件处理中"),
        ),
        migrations.AddIndex(
            model_name="fbainventory",
            index=models.Index(
                fields=["create_time"], name="api_fbainve_create__70be49_idx"
            ),
        ),
    ]
