# Generated by Django 5.2.5 on 2025-11-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_remove_fbainventory_api_fbainve_add_tim_f42782_idx_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fbainventory",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="fbainventory",
            name="update_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="更新时间"),
        ),
        migrations.AlterUniqueTogether(
            name="fbainventory",
            unique_together={
                (
                    "msku",
                    "fnsku",
                    "asin",
                    "warehouse_name",
                    "update_time",
                    "create_time",
                    "warehouse_country",
                )
            },
        ),
    ]
