# Generated by Django 5.2.5 on 2025-11-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_fbainventory_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fbainventory",
            name="update_time",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="更新时间"
            ),
        ),
    ]
