# Generated by Django 5.2.5 on 2025-11-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_alter_fbainventory_update_time"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="trafficanalysis",
            unique_together={
                ("asin", "parent_asin", "market_id", "market_name", "record_date")
            },
        ),
    ]
