# Generated by Django 5.2.5 on 2025-11-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_trafficanalysis_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="trafficanalysis",
            name="msku",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="MSKU"
            ),
        ),
    ]
