# Generated by Django 5.2.5 on 2025-11-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_trafficanalysis_msku"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="trafficanalysis",
            unique_together={
                (
                    "asin",
                    "msku",
                    "parent_asin",
                    "market_id",
                    "market_name",
                    "record_date",
                )
            },
        ),
    ]
