# Generated by Django 5.2.5 on 2025-11-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_trafficanalysis_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "待同步"),
                            ("syncing", "同步中"),
                            ("success", "同步成功"),
                            ("failed", "同步失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="同步状态",
                    ),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后同步时间"
                    ),
                ),
                (
                    "sync_message",
                    models.TextField(blank=True, null=True, verbose_name="同步消息"),
                ),
                (
                    "gerpgo_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Gerpgo ID"
                    ),
                ),
                (
                    "gerpgo_data",
                    models.JSONField(blank=True, null=True, verbose_name="原始数据"),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="货币代码"
                    ),
                ),
                (
                    "currency_symbol",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="货币符号"
                    ),
                ),
                (
                    "currency_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="货币名称"
                    ),
                ),
                (
                    "reference_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="官方汇率",
                    ),
                ),
                (
                    "custom_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="自定义汇率",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="状态"
                    ),
                ),
                (
                    "month_date",
                    models.DateField(blank=True, null=True, verbose_name="月份"),
                ),
                (
                    "last_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="最后更新日期"
                    ),
                ),
            ],
            options={
                "verbose_name": "汇率",
                "verbose_name_plural": "汇率列表",
                "indexes": [
                    models.Index(
                        fields=["currency"], name="api_currenc_currenc_9d1658_idx"
                    ),
                    models.Index(
                        fields=["month_date"], name="api_currenc_month_d_5035b5_idx"
                    ),
                ],
                "unique_together": {("currency", "month_date")},
            },
        ),
    ]
