# Generated by Django 5.2.5 on 2025-11-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_currencyrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrate",
            name="month_date",
            field=models.CharField(
                blank=True, max_length=7, null=True, verbose_name="月份"
            ),
        ),
    ]
