# Generated by Django 5.2.5 on 2025-11-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_currencyrate_month_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrate",
            name="last_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最后更新日期"
            ),
        ),
    ]
