# Generated by Django 5.2.5 on 2025-11-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_alter_adssbcreative_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="adssbcampaign",
            unique_together={("market_id", "create_date", "campaign_id")},
        ),
        migrations.AlterUniqueTogether(
            name="adssbkeyword",
            unique_together={
                (
                    "market_id",
                    "create_date",
                    "campaign_id",
                    "group_id",
                    "keyword_id",
                    "match_type",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="adssbplacement",
            unique_together={("market_id", "campaign_id", "create_date", "placement")},
        ),
        migrations.AlterUniqueTogether(
            name="adssbsearchterms",
            unique_together={
                (
                    "market_id",
                    "campaign_id",
                    "group_id",
                    "create_date",
                    "keyword_id",
                    "query",
                    "match_type",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="adssbtargeting",
            unique_together={
                ("market_id", "targeting_id", "create_date", "campaign_id", "group_id")
            },
        ),
    ]
