# Generated by Django 5.2.5 on 2025-11-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_alter_adssbcreative_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="adssbcreative",
            unique_together={
                (
                    "market_id",
                    "ad_id",
                    "campaign_id",
                    "create_date",
                    "group_id",
                    "creative_type",
                    "asins",
                )
            },
        ),
    ]
