# Generated by Django 5.2.5 on 2025-11-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_alter_adssbcreative_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adssbcreative",
            name="ads_type",
            field=models.CharField(
                default="sb", max_length=50, verbose_name="广告类型"
            ),
        ),
        migrations.AlterField(
            model_name="adssbcreative",
            name="creative_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="广告创意类型"
            ),
        ),
        migrations.AlterField(
            model_name="adssbcreative",
            name="serving_status",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="服务状态"
            ),
        ),
        migrations.AlterField(
            model_name="adssbcreative",
            name="state",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="状态"
            ),
        ),
    ]
