# Generated by Django 5.2.5 on 2025-11-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_alter_adssbcreative_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="adssdcampaign",
            unique_together={("market_id", "campaign_id", "group_id", "create_date")},
        ),
        migrations.AlterUniqueTogether(
            name="adssdproduct",
            unique_together={
                (
                    "market_id",
                    "campaign_id",
                    "group_id",
                    "create_date",
                    "ad_id",
                    "msku",
                    "asin",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="adsspkeyword",
            unique_together={
                (
                    "market_id",
                    "create_date",
                    "campaign_id",
                    "group_id",
                    "match_type",
                    "keyword_id",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="adsspplacement",
            unique_together={("market_id", "create_date", "campaign_id", "placement")},
        ),
        migrations.AlterUniqueTogether(
            name="adsspproduct",
            unique_together={
                (
                    "market_id",
                    "ad_id",
                    "create_date",
                    "campaign_id",
                    "group_id",
                    "msku",
                    "asin",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="adsspsearchterms",
            unique_together={
                (
                    "market_id",
                    "create_date",
                    "campaign_id",
                    "group_id",
                    "keyword_id",
                    "match_type",
                    "query",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="adssptarget",
            unique_together={
                (
                    "market_id",
                    "target_id",
                    "create_date",
                    "campaign_id",
                    "group_id",
                    "targeting_type",
                    "query",
                )
            },
        ),
    ]
