# Generated by Django 5.2.5 on 2026-01-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_alter_adssdcampaign_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "待同步"),
                            ("syncing", "同步中"),
                            ("success", "同步成功"),
                            ("failed", "同步失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="同步状态",
                    ),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后同步时间"
                    ),
                ),
                (
                    "sync_message",
                    models.TextField(blank=True, null=True, verbose_name="同步消息"),
                ),
                (
                    "gerpgo_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Gerpgo ID"
                    ),
                ),
                (
                    "gerpgo_data",
                    models.JSONField(blank=True, null=True, verbose_name="原始数据"),
                ),
                (
                    "market_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="市场ID"
                    ),
                ),
                (
                    "market_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="市场名称"
                    ),
                ),
                (
                    "asin",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ASIN"
                    ),
                ),
                (
                    "parent_asin",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="父ASIN"
                    ),
                ),
                (
                    "msku",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="MSKU"
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="销售日期"),
                ),
                (
                    "units_sold",
                    models.IntegerField(blank=True, null=True, verbose_name="销售数量"),
                ),
                (
                    "sales_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="销售额",
                    ),
                ),
                (
                    "traffic",
                    models.IntegerField(blank=True, null=True, verbose_name="流量"),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="转化率",
                    ),
                ),
                (
                    "avg_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="平均价格",
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="导入时间"),
                ),
            ],
            options={
                "verbose_name": "历史销售数据",
                "verbose_name_plural": "历史销售数据列表",
                "indexes": [
                    models.Index(fields=["asin"], name="api_histori_asin_073cc0_idx"),
                    models.Index(
                        fields=["market_name"], name="api_histori_market__d18ac7_idx"
                    ),
                    models.Index(fields=["date"], name="api_histori_date_dfe351_idx"),
                    models.Index(
                        fields=["imported_at"], name="api_histori_importe_333acd_idx"
                    ),
                ],
                "unique_together": {("market_name", "asin", "date")},
            },
        ),
    ]
